# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8847d08b84059d51c645e36979f622c2e7d3de3d430d18eb7e799dff86726859ee03f5082ef87402a5c5f8240e5e53af1a6bd96e60578586267c8e3dca99bfd1

test:
  secret_key_base: afa2db101ecf957c3cfecf21bd6944ffc7e4060d85e1d583ad669a29a808bf5fa63cf0d4154b48dd01c72653369260552ae0884b184a5aca0ab7b62088c68dda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
